#!/usr/bin/perl -w
use strict;
use warnings;
use Getopt::Long;
use POSIX qw( EXIT_SUCCESS EXIT_FAILURE );

use strict;

my $min = 0;
my $srcdir = "..";
my $specfile;
my @order = ();
my %file = ();
my %opts = ();

my $rc = GetOptions(
        'src=s'      => \$srcdir,
        'spec=s'     => \$specfile,
        'min=n'      => \$min,
);
die "Invalid options specified.\n" if !$rc;

length($specfile) or die "Use $0 --spec <specfile>.\n";
open(IN,"$specfile") or die "Couldn't open $specfile\n";
while (<IN>) {
        if (m/^Patch([0-9]+): (\S*)\s*$/) {
                push @order, $1;
                $file{$1} = $2;
        }

        if (m/^%patch([0-9]+) (.*\S)\s*$/) {
                $opts{$1} = $2;
        }
}
close(IN);
my $entries = @order;
printf STDERR "Read %u patches.\n", $entries;

foreach my $n (@order) {
        my $f = $file{$n};
        my $o = $opts{$n};
        print "$n $o $f\n";

        next if not defined $f;
        next if not defined $o;

        if ($n < $min) {
                warn "... skipping until we reach $min.\n";
                next;
        }

        my $p = "$srcdir/$f";
        -f $p or die "there is no $p\n";

        my $cat = "cat";
        $cat = "bunzip2 -c" if $f =~ /bz2$/;
        $cat = "gunzip -c" if $f =~ /gz$/;

        system ("$cat $p | patch -s $o")
        && die "failed to apply $n\n";

        system ("git add -u")
        && die "failed to add $n\n";

        my $do = $o;
        $do =~ s/-R//; # reverse
        $do =~ s/-E//; # ignore tabs
        
        my @mods = `$cat $p | diffstat -l $do | sed -e 's,^/,,'`;
        system ("git add @mods");

        my $empty = "";
        my $cnt = @mods;
        $empty = "--allow-empty" if $cnt < 1;

        system ("git commit $empty -m'$f ($n)'")
        && die "failed to commit $n\n";
}

system("git gc")
&& die "failed to garbage-collect\n";
