#!/bin/bash

DIRS=( $(ls -d */ | grep -v '^arch\>') arch/x86 )

if ! [ -d .git ] || ! [ -d kernel ] || ! [ -d arch ] || ! [ -f Makefile ] ; then
        echo run this script in the kernel git repo
        exit 1
fi

git grep -e '^SYSCALL_DEFINE.*(' -- "${DIRS[@]}" \
| sed -r -e 's/[,)].*//' -e 's/[:(]/ /g' \
| while read file defn syscall ; do
        #echo sed -rne '/^'"$defn.$syscall"'/,/^}/p' $file
        caps="$(sed -rne '/^'"$defn.$syscall"'/,/^}/p' $file | sed -rne 's/.*if.*\<capable\>.*\<(CAP_\S+)\>.*/\1/p')"
        echo "$syscall $file $caps"
        #exit 1
done | sort | column -t
