#!/bin/zsh
#
# This script captures a tiny distcc environment that contains only gcc.
#
# Example:
#   build-distcc-chroot sles10 root@sles-ten-host

set -e

function die {
        echo >&2 "$@"
        exit 1
}

NAME=$1
REMOTE=$2
[[ -n "$NAME" ]] || die "specify a <name> and <remote>"
[[ -n "$REMOTE" ]] || die "specify a <remote>"

mkdir -p "$1"
cd "$1"

TMP=/tmp/gcc-capture-$$

{ ssh "$REMOTE" sh <<END
set -x
touch $TMP.c
RPM_GCC=\$(rpm -qa | grep '^gcc' | xargs -n1 rpm -ql | grep 'bin/gcc\(\$\|-[0-9]\)')
DEB_GCC=\$(dpkg --get-selections 'gcc*' 2>/dev/null | awk '{ print \$1 }' | xargs -n1 dpkg -L | grep 'bin/gcc\(\$\|-[0-9]\)')
for gcc in \$RPM_GCC \$DEB_GCC ; do
    strace -f -o $TMP.log -e open \$gcc -c $TMP.c -o $TMP.o
    FILES=\$(awk -F'"' '/\<open.*= [0-9]/ { print \$2 }' $TMP.log | grep -v -e $TMP -e /tmp)
done
tar -ch -C / -f - \$FILES \$RPM_GCC \$DEB_GCC /lib*/ld*
END
} | ( sleep 1 ; tar xvf - )
